import { useEffect, useState } from 'react';
import {
  ArrowUpRight,
  CheckCircle2,
  FileCheck2,
  Github,
  LockKeyhole,
  ShieldCheck,
  TerminalSquare,
} from 'lucide-react';
import { api } from '@appdeploy/client';

type ProjectSummary = {
  artifactUrl: string;
  githubUrl: string;
  metrics: Array<{ label: string; value: string; detail: string }>;
  verification: Array<{ label: string; value: string }>;
};

const fallbackSummary: ProjectSummary = {
  artifactUrl:
    'https://github.com/ankan00V/ScalePII/raw/main/output/Red%20Herring%20Prospectus%20-%20REDACTED.docx',
  githubUrl: 'https://github.com/ankan00V/ScalePII',
  metrics: [
    { label: 'Held-out F1', value: '0.9855', detail: 'Span-level, secondary annotations' },
    { label: 'Coverage F1', value: '1.0000', detail: 'Coverage-focused sample' },
    { label: 'Unit tests', value: '40', detail: 'Synthetic and DOCX edge cases' },
  ],
  verification: [
    { label: 'Visible occurrences checked', value: '610' },
    { label: 'Hidden field occurrences checked', value: '77' },
    { label: 'Embedded images neutralized', value: '8' },
  ],
};

function App() {
  const [summary, setSummary] = useState<ProjectSummary>(fallbackSummary);
  const [apiUnavailable, setApiUnavailable] = useState(false);
  const [showBoundary, setShowBoundary] = useState(false);

  useEffect(() => {
    api
      .get('/api/project')
      .then((response) => setSummary(response.data as ProjectSummary))
      .catch(() => setApiUnavailable(true));
  }, []);

  return (
    <main>
      <nav className="nav" aria-label="Primary navigation">
        <a className="wordmark" href="#top" aria-label="ScalePII home">
          <span className="wordmark-mark"><ShieldCheck size={19} strokeWidth={2.4} /></span>
          <span>ScalePII</span>
        </a>
        <a className="nav-link" href={summary.githubUrl} target="_blank" rel="noreferrer">
          <Github size={16} /> Source <ArrowUpRight size={14} />
        </a>
      </nav>

      <section className="hero shell" id="top">
        <div className="hero-copy">
          <p className="eyebrow"><span /> PII redaction assignment</p>
          <h1>Redaction evidence,<br /><em>ready to review.</em></h1>
          <p className="lede">
            A reproducible DOCX redaction pipeline with privacy-safe audit trails,
            structural verification, and transparent evaluation evidence.
          </p>
          <div className="actions">
            <a className="button button-primary" href={summary.artifactUrl}>
              <FileCheck2 size={18} /> Download redacted DOCX <ArrowUpRight size={16} />
            </a>
            <a className="button button-secondary" href={summary.githubUrl} target="_blank" rel="noreferrer">
              <Github size={18} /> Review source
            </a>
          </div>
          <p className="microcopy">The download contains a redacted document only—never the supplied source prospectus.</p>
        </div>

        <aside className="verification-card" aria-label="Serialized document verification">
          <div className="card-topline"><span>FINAL RUN</span><span className="verified"><CheckCircle2 size={15} /> VERIFIED</span></div>
          <div className="check-illustration"><FileCheck2 size={44} strokeWidth={1.55} /></div>
          <h2>Serialized package check passed</h2>
          <p>The final DOCX is inspected at package level, including hidden field instructions and embedded media.</p>
          <dl>
            <div><dt>Structure</dt><dd>preserved</dd></div>
            <div><dt>Audit values</dt><dd>hash-only</dd></div>
            <div><dt>Media</dt><dd>neutralized</dd></div>
          </dl>
        </aside>
      </section>

      <section className="shell metrics-section" aria-labelledby="metrics-heading">
        <div className="section-heading">
          <p className="eyebrow"><span /> EVALUATION</p>
          <h2 id="metrics-heading">Measured, not hand-waved.</h2>
          <p>Scores are reported against saved annotations and clearly bounded in the evaluation report; they are not presented as a generalisation guarantee.</p>
        </div>
        <div className="metrics-grid">
          {summary.metrics.map((metric) => (
            <article className="metric" key={metric.label}>
              <p>{metric.label}</p>
              <strong>{metric.value}</strong>
              <span>{metric.detail}</span>
            </article>
          ))}
        </div>
      </section>

      <section className="shell evidence-section" aria-labelledby="evidence-heading">
        <div className="evidence-intro">
          <p className="eyebrow"><span /> DELIVERY EVIDENCE</p>
          <h2 id="evidence-heading">What the verifier actually checks.</h2>
          <p>Every claim below is generated by the included delivery verifier, not copied from a manual spot-check.</p>
        </div>
        <div className="verification-grid">
          {summary.verification.map((item) => (
            <div className="verification-item" key={item.label}>
              <strong>{item.value}</strong>
              <span>{item.label}</span>
            </div>
          ))}
        </div>
      </section>

      <section className="shell privacy-panel" aria-labelledby="privacy-heading">
        <div className="privacy-icon"><LockKeyhole size={26} /></div>
        <div>
          <p className="eyebrow"><span /> SOURCE-DOCUMENT BOUNDARY</p>
          <h2 id="privacy-heading">This hosted console does not accept source documents.</h2>
          <p>
            The supplied prospectus and gold annotations are deliberately excluded from Git and this host. The exact tested pipeline runs locally, which avoids creating an unreviewed persistence path for sensitive material.
          </p>
          <button className="text-button" type="button" onClick={() => setShowBoundary((visible) => !visible)} aria-expanded={showBoundary}>
            {showBoundary ? 'Hide' : 'Show'} local workflow <ArrowUpRight size={15} />
          </button>
          {showBoundary && (
            <pre className="command"><TerminalSquare size={16} /> python redact.py --input input.docx --output output/redacted.docx</pre>
          )}
        </div>
      </section>

      {apiUnavailable && (
        <p className="api-notice shell" role="status">
          Live summary endpoint is temporarily unavailable; static verified delivery details remain visible.
        </p>
      )}

      <footer className="shell footer">
        <span>ScalePII · DOCX PII Redaction Tool</span>
        <a href={summary.githubUrl} target="_blank" rel="noreferrer">Open repository <ArrowUpRight size={14} /></a>
      </footer>
    </main>
  );
}

export default App;
